spring.application.name=auth-service

spring.data.mongodb.uri=mongodb://mongodb-users:27017/chat-app-users

server.servlet.context-path=/auth

server.port=8081
#oauth2client

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:9999/auth/login/oauth2/code/google

#TODO: remove later
spring.thymeleaf.cache=false


server.forward-headers-strategy=framework

#eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

